MC_INITIATE = 1
MC_EXCHANGE = 2
MC_RESPONSE_INITIATE = 3
MC_RESPONSE_EXCHANGE = 4
MC_CONNECTION_END = 5

RC_SUCCESS = 0
RC_INVALID_LENGTH = 1
RC_UNKNOWN_FORMAT = 2
RC_BAD_KEY = 3

SP_NONE = 0
SP_RSA = 1
SP_AES = 2

UN_FALSE = 0
UN_TRUE = 1